name: Update IPTV Playlist
on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:        # Allow manual triggers

jobs:
  generate-playlist:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 urllib3

    - name: Configure DNS
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
        echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf > /dev/null

    - name: Network Check
      run: |
        echo "Testing connection to bdixtv.live..."
        curl --max-time 25 -Iv http://bdixtv.live/we/ || true

    - name: Generate Playlist
      run: python iptv_generator.py
      env:
        MAX_RETRIES: "3"
        TIMEOUT: "25"

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git diff-index --quiet HEAD || git commit -m "Auto-update playlist"
        git push