name: Update Playlist

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Generate playlist
      run: |
        python scripts/generator.py
        ls -la channels/  # Verify file creation

    - name: Commit changes
      env:
        REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git add channels/playlist.m3u
        git status  # Check which files are staged
        git commit -m "Auto-update playlist"
        git push