name: Update Playlist
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Generate Playlist
      run: python iptv_generator.py
      
    - name: Verify File Exists
      run: |
        ls -la
        if [ -f "playlist.m3u" ]; then
          echo "Playlist file exists"
        else
          echo "Playlist file missing!"
          exit 1
        fi
        
    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git status
        git commit -m "Auto-update playlist" || echo "No changes to commit"
        git push