name: Update IPTV Playlist

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r scripts/requirements.txt

    - name: Generate playlist
      run: |
        python scripts/generator.py
        echo "=== Generated Content ==="
        head -n 5 channels/playlist.m3u
        ls -la channels/

    - name: Commit changes
      env:
        REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Keep explicit secret name
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:$REPO_TOKEN@github.com/${{ github.repository }}
        
        # Only commit if changes exist
        if [ -n "$(git status --porcelain)" ]; then
          git add channels/playlist.m3u
          git commit -m "Auto-update playlist $(date +'%Y-%m-%d %H:%M')"
          git push origin main
        else
          echo "No changes to commit"
        fi