name: IPTV Playlist Update
on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure Network
      run: |
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 urllib3

    - name: Network Diagnostics
      run: |
        echo "--- DNS Test ---"
        nslookup bdixtv.live
        echo "--- Port Test ---"
        nc -zv bdixtv.live 80 2>&1 | grep succeeded
        echo "--- HTTP Test ---"
        curl -ILks --max-time 30 -A "Mozilla/5.0" -H "Accept-Language: en-US" http://bdixtv.live/we/

    - name: Generate Playlist
      run: python iptv_generator.py
      env:
        REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

    - name: Commit Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M UTC')"
        git push